### ISSUE TITLE
can this tool generate xml for each image annotation object? 

### ISSUE THREAD

**Issue by renguoyin123** [developer0hye/Yolo_Label#15]
Excellent Yolov3 annotation tool, can this tool generate xml for each image annotation object? Do you need Xml to train your image? What is the use of an XML file?

**Comment by renguoyin123** [comment]
How does the .xml file compare to the generated train. txt and test. Txt In the absolute path of the picture has an impact?

**Comment by renguoyin123** [comment]
I used labelImg tagging tool and saved it every time I tagged Roi. Txt and. XML File, it is not clear whether XML can not be generated, only txt.

**Comment by developer0hye** [comment]
Now, it only can support to save .txt file for annotation information.
So, do you want to save and load .xml format for annotation??

**Comment by renguoyin123** [comment]
Well, do you train without XML? The next time I will try A NON-XML TRAIN, I hope it works. thanks!

**Comment by developer0hye** [comment]
Yeap
I have trained yolov3 with .txt format! Because original yolov3 source code supports .txt files, I implemented this tool to save .txt format! Thank you for your good comments!!
