### ISSUE TITLE
Unable to open exe in Windows 10

### ISSUE THREAD

**Issue by bcsrn** [developer0hye/Yolo_Label#20]
Unable to resize the exe file to fit on laptop screen

**Comment by developer0hye** [comment]
what's resolution of your laptop screen?

**Comment by DanialV** [comment]
I have the same issue can't resize and cant see bottom of the app my resolution is 1366 * 768

**Comment by fm64hylian** [comment]
I have the same issue, it's not possible to select the buttons because of laptop resolution (1366 * 768)

**Comment by xiyi8580** [comment]
We can change the size in display setting to 100% to solve the issue temporarily.

**Comment by developer0hye** [comment]
Now YoloLabel can be runned on 1280x720 resolution.
