### ISSUE TITLE
Cant use it because it is set for 1080p resolution

### ISSUE THREAD

**Issue by DenpaBorisu** [developer0hye/Yolo_Label#21]
the max resolution for my screen is 1368x768, hence theres no way for me to reach the buttons at the bottom, sad af, pls help

**Comment by DanialV** [comment]
Same here

**Comment by sky93** [comment]
same here :)

**Comment by saduncakmakli** [comment]
Same here :/

**Comment by developer0hye** [comment]
Now YoloLabel can be runned on 1280x720 resolution.

**Comment by sky93** [comment]
Good job
