### ISSUE TITLE
Window is not resize able

### ISSUE THREAD

**Issue by STG284** [developer0hye/Yolo_Label#23]

**Comment by fm64hylian** [comment]
is there any update to this? using laptop dimensions is impossible to reach the buttons, maybe adding a file bar?

![image](https://user-images.githubusercontent.com/35852750/93034199-40ade980-f674-11ea-8e4f-2313dd177b4d.png)

**Comment by developer0hye** [comment]
@fm64hylian 

I haven't done it yet. Sorry...

**Comment by developer0hye** [comment]
Now YoloLabel can be runned on 1280x720 resolution.
