### ISSUE TITLE
saving box coords are wrong 

### ISSUE THREAD

**Issue by birolkuyumcu** [developer0hye/Yolo_Label#25]
saving coords with this code

_>             double midX     = objBox.box.x() + objBox.box.width() / 2.;
>             double midY     = objBox.box.y() + objBox.box.height() / 2.;
>             double width    = objBox.box.width();
>             double height   = objBox.box.height();_

but in Yolo 

> <object-class> <x> <y> <width> <height>
> Where x, y, width, and height are relative to the image's width and height.

not from mid

**Comment by developer0hye** [comment]
In Yolo, x and y mean the center position of object.
