### ISSUE TITLE
Remove restriction on size of bounding box

### ISSUE THREAD

**Issue by pullmyleg** [developer0hye/Yolo_Label#29]
@developer0hye the Tool is awesome, almost perfect but it would be great if there was no restriction on what size you can mark a bounding box. 

It doesn't allow small enough objects when tagging small things on a frame from a 4k video :). I have really small objects! 

Thanks!

**Comment by developer0hye** [comment]
@pullmyleg 

Thanks!

Which functions do you want to be implemented on this project?

1. zoom the image

2. remove the restriction on the image resolution

Do you want the function that can zoom the image?

**Comment by pullmyleg** [comment]
Hi @developer0hye,

I just want to be able to tag smaller objects. I don't require zoom but thanks! This feature could be helpful at times but a large enough screen also works. 

See the attached video [here](https://1drv.ms/v/s!AqW4KCCyA4HihLRrgbDCaBepv-t29g?e=bcOsK1), I think it explains better what I am trying to achieve. It seems there are minimum length and width restrictions on a bounding box at present. 

Thanks!

**Comment by developer0hye** [comment]
@pullmyleg 
Can you build qt project? 
I modified the restriction on object size. If you want a release file(*.exe), tell me.

**Comment by pullmyleg** [comment]
.exe would be great if possible?

I have not built qt project before. What are you compiling with?

Sent on the run...

________________________________

**Comment by developer0hye** [comment]
@pullmyleg 
I will try to upload .exe. But it will take some time T.T

**Comment by pullmyleg** [comment]
What do you use to compile project? No problem doing myself :). Thanks!

Sent on the run...

________________________________

**Comment by developer0hye** [comment]
please download this and test!
[download](https://drive.google.com/file/d/1lanO8SyY2QlbVCbOR0LlwQjQYbhoteTd/view?usp=sharing)

If your problem is solved, please comment on this issue

**Comment by pullmyleg** [comment]
This is great! Problem solved. Thanks, @developer0hye. Much appreciated!
