### ISSUE TITLE
Option to resize bounding box

### ISSUE THREAD

**Issue by GeoffSion** [developer0hye/Yolo_Label#31]
Hi, 
First of all: great tool, you reinvented the wheel but made it super simple and intuitive. 
I am thinking about using Yolo_Label to correct annotations automatically generated by my yolo model. The idea is to have a an automated pre-annotation, then I just need to resize the bounding boxes for perfect annotations. However, this requires a resizing mode, otherwise I will need to delete the "ok" annotation in order to make a perfect one.
Are you planning on developing such an option/mode?

Also, an image zoom would be a great addition to the projet in my opinion.
Thank you for you answer

**Comment by developer0hye** [comment]
@GeoffSion 
Thanks for your great feedback!
I thought that your idea is good.
When I have enough time to implement your recommendations, I'd modify code! But it will take looong time...
