### ISSUE TITLE
some (jpg)images are not displayed

### ISSUE THREAD

**Issue by fm64hylian** [developer0hye/Yolo_Label#35]
sometimes .jpg (not .png or .jpeg) images are not displayed on the UI, if there are a lot of images, neither using the slider or the prev next buttons will display the image, the path will be updated tho.

I tried isolating the image what was not being shown, but it doesn't work either:
![yoloissue](https://user-images.githubusercontent.com/35852750/91149083-9d615880-e6f5-11ea-894d-2a16df5f09e3.png)

I am working with relatively small sets (less than 100 images per labeling session) so I don't know if this becomes more often with larger amounts.

although it's kind of random, is there a way to fix this? 

thank you.

**Comment by developer0hye** [comment]
Can you share the image files that have problems?

**Comment by fm64hylian** [comment]
Thank you for your reply, these are the ones not being displayed (all .jpg): 
![asparagus_0076](https://user-images.githubusercontent.com/35852750/91248289-4d36d480-e78f-11ea-8dad-0af475a691ef.jpg)
![asparagus_0103](https://user-images.githubusercontent.com/35852750/91248294-4f009800-e78f-11ea-8aec-b52f0fcd4a9a.jpg)
![asparagus_0163](https://user-images.githubusercontent.com/35852750/91248300-5031c500-e78f-11ea-860f-6c35b253f227.jpg)

**Comment by developer0hye** [comment]
It seems that the decoder in QT can not decode some jpg files, you should convert jpg format to png format. When I change the image format, it is displayed.

**Comment by fm64hylian** [comment]
I see, ok I tried something weird, but I converted to png and then converted back to jpg, and now they are displayed.
So I guess it is a good solution for now, Thank you!
