### ISSUE TITLE
some image coords are not being saved

### ISSUE THREAD

**Issue by fm64hylian** [developer0hye/Yolo_Label#36]
I have hundreds of images correctly being saved but there's these 2 jpg images where no matter how I save, the coords are not being added to the txt file:
![error1](https://user-images.githubusercontent.com/35852750/92704600-04d20600-f38e-11ea-91c1-131f804cbf84.jpg)
![error2](https://user-images.githubusercontent.com/35852750/92704616-07346000-f38e-11ea-809f-a0dc179836f7.jpg)

for some reason, only the, percentages? are being saved. These two images are the only ones where this is happening. I tried with another 600 images(jpg and png) and both fields are being saved. What could it be?

Thank you

**Comment by developer0hye** [comment]
@fm64hylian 
Can you send me these files?

**Comment by fm64hylian** [comment]
sorry for the late reply. these are the files:

![carrot_0120](https://user-images.githubusercontent.com/35852750/93033805-c92b8a80-f672-11ea-9f7d-a4aeb07919ba.jpg)
![carrot_0106](https://user-images.githubusercontent.com/35852750/93033806-ca5cb780-f672-11ea-80f9-51e011bbc595.jpg)

I'm running a script to resize some images using opencv, I don't know if that could be the cause

**Comment by developer0hye** [comment]
@fm64hylian 
what size do you resize?

**Comment by fm64hylian** [comment]
it's not a small size, those are the resized images^, my script will only resize in half if the image is over 1000px, so a image will never be smaller than 500px. My darknet model resizes at 416px anyway

**Comment by developer0hye** [comment]
https://github.com/developer0hye/Yolo_Label/blob/e002e18a1663c8c9b0a5548d4a2fc38649bd18e3/label_img.cpp#L56-L57

Look at the above condition, if your bounding box is too small, the box would not be saved. Can you check this?

**Comment by fm64hylian** [comment]
I'm really sorry, I was mistaking the labelling format with a different labelling tool, other tools label like 0 214 332 145 423 etc and I was getting mixed formats when saving the labels, so it is labelling correctly.

Unfortunately, I cannot check on my laptop because the insufficient resolution issue, but thanks.

the code is the same btw:
```
bool width_is_too_small     = objBoundingbox.box.width() * m_inputImg.width()  < 4;
bool height_is_too_small    = objBoundingbox.box.height() * m_inputImg.height() < 4;
```

Sorry for the misunderstanding.

**Comment by developer0hye** [comment]
@fm64hylian 
It's okay~!
