### ISSUE TITLE
Filter out already marked images

### ISSUE THREAD

**Issue by guybashan** [developer0hye/Yolo_Label#37]
Thanks for the great tool.
It might be convenient to have an option to filter out an image that has at least one label.
In many cases I am adding new images and don't want to skip the ones that are already marked.
It is especially convenient when there is a big amount of images.

**Comment by developer0hye** [comment]
@guybashan 
I think that it is a good option. But my goal is to develop program that can generally be used. It seems that this option is needed for few users. I recommend you manage two folders, labeled and unlabeled folder.

If many people propose the issue like this, I will add this function!

Thanks for your good idea!
