### ISSUE TITLE
no CSV export

### ISSUE THREAD

**Issue by ajaysurya1221** [developer0hye/Yolo_Label#39]
TrainYourOwnYOLO requires CSV file as data. Is there any way we can do that with Yolo_Label?

**Comment by developer0hye** [comment]
@ajaysurya1221 

Annotate your data with Yolo_Label and then change the '.txt' ext of annotation file to '.csv'

I also recommend you to use another yolo projects that support '.txt' files.

**Comment by ajaysurya1221** [comment]
Hi may I please know the order of the bounding box data in .txt file ?
is it xmin ymin xmax ymax?

**Comment by developer0hye** [comment]
No, it is class center_x center_y width height.

**Comment by ajaysurya1221** [comment]
Thanks a lot. Is there any formula or pseudocode to convert these values into xmin ymin xmax and ymax ?

**Comment by developer0hye** [comment]
x y w h

xmin = x - w / 2
ymin = x - h / 2
xmax = x + w / 2
ymax = y + h / 2
