### ISSUE TITLE
Program does not work

### ISSUE THREAD

**Issue by kchpomp** [developer0hye/Yolo_Label#44]
Doing everything according to guide. However, the program does not work properly.
I add image directory, then file with class names. Then names do not appear in the programm and I cannot draw bounding boxes.

**Comment by developer0hye** [comment]
@kchpomp 
Did you test with samples?

**Comment by kchpomp** [comment]
Yes. Actually, the problem was solved. The key was that folder names were on Russian language, when I switched them on English, the program started to work.
