### ISSUE TITLE
The dll I use to run the existing .exe and the dll in the .exe built by qt are different and I get a lot of disconnections when moving the mouse. Can you see why?

### ISSUE THREAD

**Issue by c1jm77** [developer0hye/Yolo_Label#45]
1. When I run it in debug mode, the dll looks different. Like Qt5cored.dll, d is added. Does this issue affect mouse hangup?

2. Mouse crosses are very slow to follow. And it got worse when the window was maximized.
The readme's window and the current window look different and updated, but where is the object name and color part cut off the color part? In other words, is it because the slider bar that pushes it to the side is below it?
(한국인이시면 한국어로 해주시면 감사하겠습니다.)

**Comment by c1jm77** [comment]
debug mode run.............. sorry

**Comment by c1jm77** [comment]
There is still stuttering when maximizing the program. And the list of objects is truncated.

**Comment by developer0hye** [comment]
해결됐다니 다행입니다 ^^~

**Comment by c1jm77** [comment]
[image: image.png]
답변 감사합니다. ㅎㅎ
전체화면에서 버벅거림은 따로 call back이나 Thread를 넣어야될까요?
그리고 사진은 build시 바로 뜨는 창인데 창크기 상관없이 오른쪽 List 부분이 짤림현상이 생겨서..  원래되는 부분인데 제가
여전히 못찾고있는건지..? (이게 마지막 댓글이었어요.)  도움주시면 감사하겠습니다.

2021년 3월 4일 (목) 오후 9:48, Yonghye Kwon <notifications@github.com>님이 작성:

**Comment by developer0hye** [comment]
1. 해상도가 어떻게 되나요?
2. 짤림현상에 대해 사진을 첨부해주시길 바랍니다.

**Comment by c1jm77** [comment]
해상도 3840 x 2160이고, 짤림 현상은 위에 글에 있는데 혹시 안보이신가욤? (List 부분의 Color와 아래 슬라이더바 /
Log창 check Box부분)

2021년 3월 5일 (금) 오후 12:19, Yonghye Kwon <notifications@github.com>님이 작성:

**Comment by developer0hye** [comment]
아.. 4k 해상도에서 리사이징에 필요한 연산량이 많은지 버벅이더라고요. 라벨링할땐 fhd 해상도에서 합니다. 네 사진이 안보이네요 ㅜ

**Comment by c1jm77** [comment]
[image: image.png]
사진은 첨부로 넣었어용 오른쪽 object list랑 Log부분이 짤려있더라구용 UI적인거 수정하면 되는거같아 했는데 됬는데 이게
맞는건징
지금 첨부사진은 수정전 github에서 받을때 상태입니다.

2021년 3월 5일 (금) 오후 6:19, Yonghye Kwon <notifications@github.com>님이 작성:

**Comment by developer0hye** [comment]
@c1jm77 
아 안짤리는 게 맞습니다. 시간날때 한 번 수정해보도록 하겠습니다. 아니면 풀리퀘스트 보내주시면 머지하도록 하겠습니다.

**Comment by c1jm77** [comment]
UI는 제가 수정 해봤는데 Layout때문에 처음 접해봐서 고생했네요.

2021년 3월 8일 (월) 오후 7:14, Yonghye Kwon <notifications@github.com>님이 작성:

**Comment by developer0hye** [comment]
@c1jm77 

맞습니다. 지금은 리사이징시 종횡비를 고려하지 않고 있습니다. 종횡비를 고려하려면 이미지 리사이즈 방법을 수정해야합니다.

letter box resize method, aspect ratio preserved image resize method 등의 키워드로 검색해보시면 감이 오실듯 합니다.

https://github.com/developer0hye/YOLOv3Tiny/blob/c6df418ca0c5949386412a57423ad4bed691f547/augmentation.py#L25-L72

구현하면 좋은 기능이나 최대한 심플하게 구현하는 걸 목표로 삼았었기에 해당 기능을 구현하지 않았습니다.

**Comment by c1jm77** [comment]
답변 감사 드려요.
근데 아직 종회비를 찾고있지만 감이 덜 온 것 같아요... ㅎㅎ 좀더 봐야할꺼같습니다.

혹시 궁금한게 생겼는데 답변가능 하신가요?
Source 구조를 이해 햇다고 대충봤지만 좀더 깊게보니 이해가안되서 label_img.cpp와 mainwindow.cpp 가있는데
ui와 어떤구조/연관인지 찾기가 힘드네요.
mainwindow.cpp에서 ui->label_image->openImage(m_imgList.at(m_imgIndex),
bImgOpened); 이런식으로 쓰고있어서 ui와  mainwindow.cpp는 연결은 되있는거같다?(추측성이고),
m_imgList는 data들 List인데 openImage 함수에서 m_inputImg에 copy되서 사용되고있는거 같고, 하지만
label_img와  mainwindow.cpp의 연결 관계는 못찾은 상태입니다. ㅠㅠ

data영역?이라고 해야할까요? 이미지에 대한 data부분을 구조체로 나누려면 어떤것들이 있을까요?  (m_inputImg 이 부분만
찾은거 같아요..)

아직 개발어린이라.. 도와주실수 있으신 부분 답변 해주시면 감사하겠습니다 ㅜㅜ..

2021년 3월 9일 (화) 오후 8:35, Yonghye Kwon ***@***.***>님이 작성:

**Comment by developer0hye** [comment]
mainwindow는 전반적인 ui 구성과 이벤트를 다룹니다. 그중의 일부가 label_image입니다. 그리고 label_image 클래스는 mainwindow에서 화면이 출력되는 frame 영역내에서 발생하는 마우스 이벤트를 처리하며 그 이벤트에 따라 적절하게 이미지 상에 박스나 크로스라인을 그립니다. 이미지에 대한 data 부분을 접근하려면 label_image내에 m_inputImg 객체를 접근하면 됩니다. 이는 QImage 클래스의 객체로 QImage 를 공부해보시면 될 거 같습니다.

**Comment by c1jm77** [comment]
답변 감사합니다.
바쁘다보니 해상도 종횡비 찾다찾다 이제야 했지만, 문제가생겨.. 메일 보냅니다. ㅠㅠ
제가 테스트로 화면 두개로 만들어 놓고 사용중입니다.
그런데 scaled에서 옵션을 IgnoreAspectRatio일때는 양쪽다 박스위치가 동일하고 crossline도 잘됬는데,
KeepAspectRatio를 사용하니 crossline이 마우스 커서와 다르게 움직이고 있습니다.
두 옵션의 의미는 알겠으나 crossline과 drawFocusedObjectBox에 영향이 끼치는 이유를 못찾겠네용... ㅠㅠ
바쁘실텐데 귀찮게 해서 죄송해요.

2021년 3월 15일 (월) 오후 9:28, Yonghye Kwon ***@***.***>님이 작성:

**Comment by developer0hye** [comment]
@c1jm77 흠... 저도 언급하신 부분에 대해서는 잘 모르겠네요... KeepAspectRatio로 이미지를 출력했을때 aspect ratio 를 유지한채로 리사이즈가 되었나요?

**Comment by c1jm77** [comment]
덕분에 원하는 프로그램으로 만들었네용 ㅎㅎ..
이제 3D를 할 예정인데 혹시 아시는 내용이있으신가요?.. 개념적으로 아직 부족하네용
openGL로 할지 Vulkan으로 할지 고민되서... 그래픽관련 개념이없으면 openGL을 사용하라는 말들이 많긴해서 ㅠㅠ.. 혹시
다루어보셨나욤?

2021년 3월 23일 (화) 오후 8:38, Yonghye Kwon ***@***.***>님이 작성:

**Comment by developer0hye** [comment]
@c1jm77 
아니요 ㅜ 3D는 다뤄보지 못했습니다. 해내셨다니 멋지시네요. 축하드립니다!
