### ISSUE TITLE
How to use resulting .txt?

### ISSUE THREAD

**Issue by Nprime496** [developer0hye/Yolo_Label#46]
Hi , a little documentation on the result file would be appreciable.

PS: the software is incredibly simple and powerful 👍 

:( However about HCI, some improvements could be:
- **"remove"** button should not be aside "save" button (deleted some of my samples stupidly and cannot retrieve them, a validation box can be appreciable)
- tips about where " remove" button sends your beloved samples (tooltips on each button can be appreciable)
- " change directory " and " open files " buttons : I don't know the difference and they are too close from "save" button although they are not used so often also clicking on them is not cancelable

**Comment by developer0hye** [comment]
@Nprime496 

Good Idea!
I think that if you can deal QT library, you should do pull request after editing these improvements!

Can you do that?
