### ISSUE TITLE
img number issue

### ISSUE THREAD

**Issue by haviduck** [developer0hye/Yolo_Label#48]
Hello, thanks for making a cool annotation tool.
We are trying it out but facing an issue with the numbering. when we switch from img#109 to 110 it instead goes to 1001. i cant find the relevant code in source, but would love any pointers or a fix.  im on win so compiling is abit iffy aswell.

**Comment by developer0hye** [comment]
@haviduck 
Hi, haviduck!

You make a good point. I knew this issue, but no one had made a point about this issue.

I modified code so that file name will be sort naturally.

Could you check this again?

**Comment by haviduck** [comment]
> @haviduck
> Hi, haviduck!
> 
> You make a good point. I knew this issue, but no one had made a point about this issue.
> 
> I modified code so that file name will be sort naturally.
> 
> Could you check this again?

ah great, thank you and ill check as soon as possible. its not a big deal except for when i collab on datasets, this gonna save us some time.

**Comment by developer0hye** [comment]
@haviduck 
Okay! After check this issue, please tell me again~

**Comment by fsanne** [comment]
Can confirm it works!

**Comment by developer0hye** [comment]
@fsanne 
In my pc, it works on winodws!

**Comment by fsanne** [comment]
> @fsanne
> In my pc, it works on windows!

Yeah same, so you can close the issue =) It was opened by my colleague so I'll let him know.

**Comment by developer0hye** [comment]
@fsanne 
Thanks~

**Comment by fsanne** [comment]
By the way, if this would generate a train.txt with the path to the annotation files it would be absolutely perfect! Yolo mark as you know does that, but I really like yolo label better. It feels more effortless and I prefer the gui as well.
