### ISSUE TITLE
rotating

### ISSUE THREAD

**Issue by nchesk** [developer0hye/Yolo_Label#49]
tool randomly rotates images 

look how picture looks like in labeling tool 
![Capture](https://user-images.githubusercontent.com/29508676/120898836-6e3d2780-c635-11eb-8d18-042faa427807.PNG)

and in my folder

![cqcds](https://user-images.githubusercontent.com/29508676/120898840-7301db80-c635-11eb-9b1b-22d4626951a3.PNG)

**Comment by developer0hye** [comment]
@nchesk 
Can you send me example images?

**Comment by developer0hye** [comment]
@nchesk I fix this issue.

download this https://drive.google.com/file/d/1h_7LRm-dYX3D653A1Sb6Mq0iWxjzugNw/view?usp=sharing

**Comment by nchesk** [comment]
thanks!)
you're awesome)
