### ISSUE TITLE
Command Line Functions

### ISSUE THREAD

**Issue by andrewwetzel23** [developer0hye/Yolo_Label#54]
Is there potential to add functionality to set the image directory and object text file from the command line?

**Comment by developer0hye** [comment]
@andrewwetzel23 
Is this function important to you?

**Comment by andrewwetzel23** [comment]
It would be very helpful for including this program in an active learning loop.

**Comment by developer0hye** [comment]
@andrewwetzel23 
Okay, I will try to implement this function by next week!

**Comment by andrewwetzel23** [comment]
I appreciate that immensely.

**Comment by developer0hye** [comment]
@andrewwetzel23 

Test with the below file.

[cmd-yololabel.zip](https://github.com/developer0hye/Yolo_Label/files/9439171/cmd-yololabel.zip)

# Usage
```
./YoloLabel.exe dataset_path label.txt
```

**Comment by andrewwetzel23** [comment]
Works great. Thanks for the quick turnaround!

**Comment by andrewwetzel23** [comment]
Are you able to send me the source code for that function being implemented? I am hoping to build it for Linux.
